---
- name: Generate DR audit report
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Display DR audit information
      ansible.builtin.debug:
        msg:
          - "Consistency Group : {{ consistency_group_name }}"
          - "Service Stop Start: {{ service_stop_start_time }}"
          - "Service Stopped   : {{ service_stop_time }}"
          - "Failover Started  : {{ failover_start_time }}"
          - "Failover Completed: {{ failover_complete_time }}"
          - "Service Start     : {{ service_start_time }}"
          - "Service UP        : {{ service_up_time }}"

