---
- name: Validate recovered Windows VMs
  hosts: DESKTOP-N0JKB4D
  gather_facts: false

  tasks:

    - name: Wait for Windows boot and WinRM connectivity
      ansible.builtin.wait_for_connection:
        timeout: 600
        sleep: 10
        connect_timeout: 5

    - name: Validate Windows management connectivity
      ansible.windows.win_ping:
      register: windows_ping_result

    - name: Display Windows connectivity result
      ansible.builtin.debug:
        msg:
          - "VM: {{ inventory_hostname }}"
          - "IP: {{ ansible_host }}"
          - "Windows connectivity: SUCCESSFUL"
          - "Win Ping response: {{ windows_ping_result.ping }}"
