---
- name: Validate recovered Windows VMs
  hosts: DESKTOP-N0JKB4D
  gather_facts: false

  tasks:

    - name: Validate Windows management connectivity
      ansible.windows.win_ping:
      register: windows_ping_result

    - name: Display Windows connectivity result
      ansible.builtin.debug:
        msg:
          - "VM: {{ inventory_hostname }}"
          - "IP: {{ ansible_host }}"
          - "Windows connectivity: SUCCESSFUL"
          - "Win Ping response: {{ windows_ping_result.ping }}"
